version: "3.8"

services:
  rest-api:
    container_name: rest_api_service
    build: .
    ports:
      - "3000:3000"
    env_file: 
      - .env
    depends_on:
      - postgres_db
    volumes:
      - ./:/app
    networks:
      - api-postgres_db

  postgres_db:
    image: postgres:latest
    container_name: postgres_wbd
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - api-postgres_db

volumes:
  postgres_db:
    driver: local

networks:
  api-postgres_db:
    driver: bridge